// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAucGHpJLtKWjnvGc_NjXNW4aKTPiWhwq8',
    appId: '1:356494059919:web:ee626359f715e2af1683fa',
    messagingSenderId: '356494059919',
    projectId: 'mi-app-gastos-d6566',
    authDomain: 'mi-app-gastos-d6566.firebaseapp.com',
    storageBucket: 'mi-app-gastos-d6566.firebasestorage.app',
    measurementId: 'G-LT8MC9RNT1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgXUw5UiVSmt8YymX5f4VNszj0Vjib-Qg',
    appId: '1:356494059919:ios:23e39e8cffafe4491683fa',
    messagingSenderId: '356494059919',
    projectId: 'mi-app-gastos-d6566',
    storageBucket: 'mi-app-gastos-d6566.firebasestorage.app',
    iosBundleId: 'com.example.arigastosapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgXUw5UiVSmt8YymX5f4VNszj0Vjib-Qg',
    appId: '1:356494059919:ios:5543123c15cb46051683fa',
    messagingSenderId: '356494059919',
    projectId: 'mi-app-gastos-d6566',
    storageBucket: 'mi-app-gastos-d6566.firebasestorage.app',
    iosBundleId: 'com.example.arigastos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAucGHpJLtKWjnvGc_NjXNW4aKTPiWhwq8',
    appId: '1:356494059919:web:f5a9277738f857e41683fa',
    messagingSenderId: '356494059919',
    projectId: 'mi-app-gastos-d6566',
    authDomain: 'mi-app-gastos-d6566.firebaseapp.com',
    storageBucket: 'mi-app-gastos-d6566.firebasestorage.app',
    measurementId: 'G-EL7KH2V3JD',
  );
}
